# -*- coding: utf-8 -*-
"""breast cancer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p4z8evyHn-VsGDo_efaDiS6UGmnBxTzd
"""

import matplotlib.pyplot as plt 
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

cancer = load_breast_cancer()
print (cancer.keys())
cancer_df = pd.DataFrame(cancer.data, columns=cancer.feature_names)
print (cancer_df.head(3))
X = cancer.data
Y = cancer.target

X_train,X_test,y_train,y_test=train_test_split(X,Y, test_size=0.3, random_state=31)

lr = LinearRegression()
lr.fit(X_train,y_train)
lr_train_score=lr.score(X_train,y_train)
lr_test_score=lr.score(X_test,y_test)
print ("LR training score:", lr_train_score )
print ("LR test score: ", lr_test_score)  x~az

from sklearn.linear_model import Lasso

lasso = Lasso()
lasso.fit(X_train,y_train)
train_score=lasso.score(X_train,y_train)
test_score=lasso.score(X_test,y_test)
coeff_used = np.sum(lasso.coef_!=0)
print ("training score:", train_score )
print ("test score: ", test_score)